### PR TITLE
Use omero-cli-transfer to send archives to iRODS

### PR DESCRIPTION
**Pull request by joshmoore**
Despite many hard-codings custom to this sandbox (user, password, etc.), this script permits running the `omero transfer pack` command to create an archive for the chosen images and send them to iRODS.

Simple reproducer:

```
cd server
touch a.fake
IMAGE=$(omero import a.fake)
omero script upload --official Send_to_iRODS.py
omero script launch /Send_to_iRODS.py IDs=${IMAGE##Image:}
````

A file named `transfer.tar` will now exist in the iRODS zone.

### CODE REVIEW

**Comment by trel** [comment]
Nice!   Yes, definitely some additional parameter work to be done.
 
Okay - so we need a tweak to the docker-compose.yml file as well to get these into the stood-up OMERO, rather than just the direct-from-dockerhub we are using now...

https://github.com/irods-contrib/irods_working_group_imaging/blob/fee73a3c56f1612abb21906e0a50f25e8e4a8b68/sandbox/docker-compose.yml#L32

**Comment by joshmoore** [comment]
Anything `>=5.6.10` should work since that is when the Python version got bumped. All the following currently point to 5.6.10:
 * 5
 * 5.6
 * latest
 * 
but I bumped it here since not everyone will think to `docker compose pull` beforehand.

**Comment by trel** [comment]
gotcha.  i'm going to reproduce some success without handholding... see how far i get.

**Comment by trel** [comment]
success!

with my additional commit... https://github.com/irods-contrib/irods_working_group_imaging/pull/30/commits/cc56e431a0a2bc84d672e159e4186729a6460f50
part of #30 

-----


on host:
```
docker exec -it sandbox-omero-1 bash
```

in docker (as omero-server user (user 1000)):
```
cd /opt/omero/server
source venv3/bin/activate
touch a.fake
omero login --server localhost --port 4064 --user root --password omero-root-password
IMAGE=$(omero import a.fake)
omero script upload --official Send_to_iRODS.py
omero script launch /Send_to_iRODS.py IDs=${IMAGE##Image:}
```

on the host ... success:
```
$ docker exec -it -u irods sandbox-irods-catalog-provider-1 ils -l
/tempZone/home/rods:
  rods              0 demoResc        20480 2024-01-12.02:43 & transfer.tar
```

-----

no NFSRODS in sight.

**Comment by trel** [comment]
This success was performed standalone from Josh's AWS instance.  Should work for anyone else who may want to confirm as well.

**Comment by joshmoore** [comment]
Thanks for the confirmation, @trel. From my side, feel free to spin down the host (if you haven't already).

cc: @glyg @erickmartins for discussion at the WG meeting tomorrow (3PM UTC)

**Comment by trel** [comment]
> feel free to spin down the host

it is done.

**Comment by joshmoore** [comment]
Points for discussion at the next meeting:

 - `target path`: An update to this PR means that the user is now responsible for filling in a path.
 - `username`: probably the best strategy I can think of would be to add an annotation in the "irods" namespace to users. Is this the best next step?
 - `versioning`: current suggestion from the omero-cli-transfer team would be to pin the installed version of transfer to that of the archives. (An upgrade would require re-creation)
 - anyone want to test?

**Comment by trel** [comment]
#30 has new things...

- Save/Export
  - Added overwrite protection
  - Confirmed Exceptions are logged by OMERO
  - Added as_user proxy to script
- Load/Import
  - Added transfer_from_irods
  - Don't know the OMERO call/syntax for writing, yet

**Pull request closed without merging**
